export {
  getDashboard,
  getAnalytics,
  getDailyRevenue,
  listUsers,
  toggleUserBlock,
  deleteUser,
  listProducts,
  getProductById,
  generateAdminProductNumber,
  createProduct,
  updateProduct,
  uploadAdminProductImages,
  deleteProduct,
  approveProduct,
  rejectProduct,
  getProductStats,
  listCategories,
  createCategory as createAdminCategory,
  updateCategory as updateAdminCategory,
  toggleCategory as toggleAdminCategory,
  listOrders,
  updateOrderStatus,
  getAuditLogs,
  getStaffPermissionCatalog,
  listStaffRoles,
  createStaffRole,
  updateStaffRole,
  deleteStaffRole,
} from "./adminApi";
