import {
  BarChart3,
  Brush,
  Boxes,
  CreditCard,
  FileSearch,
  Film,
  FolderTree,
  Target,
  Image,
  Lightbulb,
  MessageSquare,
  LayoutDashboard,
  Package2,
  Palette,
  Percent,
  RotateCcw,
  Settings,
  ShieldCheck,
  ShoppingCart,
  Star,
  Tags,
  Truck,
  Users,
  Wallet,
  Wrench,
} from "lucide-react";

export const ADMIN_PRIMARY_ITEM = {
  name: "Dashboard",
  path: "/admin/dashboard",
  icon: LayoutDashboard,
};

export const ADMIN_SECTION_ITEMS = [
  {
    section: "Overview",
    key: "overview",
    items: [
      { name: "Analytics", path: "/admin/analytics", permission: "analytics.read", icon: BarChart3 },
      { name: "Revenue", path: "/admin/revenue", permission: "analytics.read", icon: Wallet, legacyOnly: true },
      { name: "Audit Logs", path: "/admin/audit-logs", permission: "audit.read", icon: FileSearch, legacyOnly: true },
    ],
  },
  {
    section: "Management",
    notificationModule: "MANAGEMENT",
    key: "management",
    items: [
      { name: "Users", path: "/admin/users", permission: "users.read", icon: Users, notificationModule: "MANAGEMENT", notificationSubModule: "USERS" },
      { name: "Products", path: "/admin/products", permission: "products.read", icon: Boxes, notificationModule: "MANAGEMENT", notificationSubModule: "PRODUCTS" },
      { name: "Inventory", path: "/admin/inventory", permission: "products.read", icon: Package2, notificationModule: "MANAGEMENT", notificationSubModule: "INVENTORY" },
      { name: "Orders", path: "/admin/orders", permission: "orders.read", icon: ShoppingCart, notificationModule: "MANAGEMENT", notificationSubModule: "ORDERS" },
      { name: "Services Requests", path: "/admin/service-requests", permission: "orders.read", icon: Wrench, notificationModule: "MANAGEMENT", notificationSubModule: "ORDERS" },
      { name: "Reviews", path: "/admin/reviews", permission: "products.read", icon: Star, notificationModule: "MANAGEMENT", notificationSubModule: "PRODUCTS" },
      { name: "Reels & Shorts", path: "/admin/reels", permission: "products.read", icon: Film, notificationModule: "MANAGEMENT", notificationSubModule: "REELS" },
      { name: "Reels Attribution", path: "/admin/reels/attribution", permission: "analytics.read", icon: Target, notificationModule: "MANAGEMENT", notificationSubModule: "REELS" },
    ],
  },
  {
    section: "Catalog",
    key: "catalog",
    items: [
      { name: "Categories", path: "/admin/categories", permission: "categories.read", icon: FolderTree, legacyOnly: true },
      { name: "Subcategories", path: "/admin/subcategories", permission: "categories.read", icon: Tags, legacyOnly: true },
      { name: "Attributes", path: "/admin/attributes", permission: "categories.read", icon: Tags, legacyOnly: true },
      { name: "Product Modules", path: "/admin/product-modules", permission: "categories.read", icon: Boxes, legacyOnly: true },
      { name: "Banner Management", path: "/admin/homepage-banners", permission: "settings.read", icon: Image },
      { name: "Custom T-Shirt Banners", path: "/admin/custom-tshirt-banners", permission: "settings.read", icon: Image },
      { name: "Custom T-Shirt Colors", path: "/admin/custom-tshirt-colors", permission: "settings.read", icon: Palette },
      { name: "Homepage Containers", path: "/admin/homepage-containers", permission: "settings.read", icon: Image },
      { name: "Homepage Builder", path: "/admin/marketing/homepage-builder", permission: "settings.read", icon: LayoutDashboard },
    ],
  },
  {
    section: "Commerce Intelligence",
    key: "commerce-intelligence",
    items: [
      { name: "Recommendation Settings", path: "/admin/commerce-intelligence/settings", permission: "settings.update", icon: Lightbulb },
      { name: "Related Products Engine", path: "/admin/commerce-intelligence/related-products", permission: "analytics.read", icon: Lightbulb },
      { name: "Frequently Bought Together", path: "/admin/commerce-intelligence/frequently-bought-together", permission: "analytics.read", icon: Lightbulb },
      { name: "Cross Sell Rules", path: "/admin/commerce-intelligence/cross-sell", permission: "settings.update", icon: Lightbulb },
      { name: "Upsell Rules", path: "/admin/commerce-intelligence/upsell", permission: "settings.update", icon: Lightbulb },
      { name: "Recommendation Analytics", path: "/admin/commerce-intelligence/analytics", permission: "analytics.read", icon: BarChart3 },
      { name: "AI Scoring Rules", path: "/admin/commerce-intelligence/ai-scoring", permission: "settings.update", icon: Lightbulb },
      { name: "Recommendation Preview", path: "/admin/commerce-intelligence/preview", permission: "analytics.read", icon: FileSearch },
      { name: "Cache Management", path: "/admin/commerce-intelligence/cache", permission: "settings.update", icon: RotateCcw },
    ],
  },
  {
    section: "Finance",
    notificationModule: "FINANCE",
    key: "finance",
    items: [
      { name: "Payments", path: "/admin/payments", permission: "payments.read", icon: CreditCard, notificationModule: "FINANCE", notificationSubModule: "PAYMENTS" },
      { name: "Refunds", path: "/admin/refunds", permission: "payments.read", icon: RotateCcw, notificationModule: "MANAGEMENT", notificationSubModule: "RETURNS" },
      { name: "Cancellation Policies", path: "/admin/finance/cancellation-policies", permission: "settings.read", icon: ShieldCheck, notificationModule: "FINANCE", notificationSubModule: "SETTINGS" },
      { name: "Invoices", path: "/admin/finance/invoices", permission: "orders.read", icon: FileSearch, notificationModule: "FINANCE", notificationSubModule: "PAYMENTS" },
    ],
  },
  {
    section: "Communications",
    key: "communications",
    items: [
      { name: "WhatsApp Logs", path: "/admin/communications/whatsapp-logs", permission: "orders.read", icon: MessageSquare },
    ],
  },
  {
    section: "Workspace",
    notificationModule: "WORKSPACE",
    key: "workspace",
    items: [
      { name: "Settings", path: "/admin/settings", permission: "settings.update", icon: Settings, notificationModule: "WORKSPACE", notificationSubModule: "SETTINGS" },
      { name: "Company Branding", path: "/admin/settings/company-branding", permission: "branding.view", icon: Brush, notificationModule: "WORKSPACE", notificationSubModule: "SETTINGS" },
      { name: "Theme Engine", path: "/admin/theme-engine", permission: "theme.view", icon: Palette, notificationModule: "WORKSPACE", notificationSubModule: "SETTINGS" },
      { name: "Shipping", path: "/admin/shipping", permission: "settings.update", icon: Truck },
      { name: "Pricing", path: "/admin/pricing", permission: "settings.update", icon: Percent },
      { name: "Pricing Categories", path: "/admin/pricing-categories", permission: "settings.update", icon: Tags },
    ],
  },
];
