const ADMIN_ROLES = ["admin", "super_admin", "support_admin", "finance_admin"];

const ALL_PERMISSIONS = [
  "dashboard:read",
  "analytics:read",
  "users:read",
  "users:create",
  "users:update",
  "users:delete",
  "vendors:read",
  "vendors:approve",
  "vendors:reject",
  "vendors:delete",
  "orders:read",
  "orders:update",
  "orders:cancel",
  "products:read",
  "products:create",
  "products:update",
  "products:delete",
  "products:approve",
  "products:reject",
  "categories:read",
  "categories:create",
  "categories:update",
  "roles:read",
  "roles:create",
  "roles:update",
  "roles:delete",
  "staff:read",
  "staff:create",
  "staff:update",
  "staff:delete",
  "audit:read",
  "payments:read",
  "payments:refund",
  "payouts:read",
  "payouts:process",
  "settlements:read",
  "settlements:settle",
  "settlements:hold",
  "settlements:release",
  "settlements:reverse",
  "settlements:payout",
  "settings:read",
  "settings:create",
  "settings:update",
  "settings:delete",
  "branding:view",
  "branding:create",
  "branding:update",
  "branding:delete",
  "recommendation:view",
  "recommendation:manage",
  "recommendation:rebuild",
  "recommendation:cache:clear",
  "influencerCommerce:read",
  "influencerCommerce:manage",
  "influencerCommerce:export",
  "influencerCommerce:settings",
];

const ROLE_PERMISSIONS = {
  admin: ALL_PERMISSIONS,
  super_admin: ALL_PERMISSIONS,
  support_admin: [
    "dashboard:read",
    "users:read",
    "users:create",
    "users:update",
    "vendors:read",
    "vendors:approve",
    "vendors:reject",
    "orders:read",
    "orders:update",
    "orders:cancel",
    "products:read",
    "payments:read",
    "payments:refund",
    "payouts:read",
    "payouts:process",
    "settlements:read",
    "settings:read",
    "settings:create",
    "settings:update",
    "settings:delete",
    "branding:view",
    "branding:create",
    "branding:update",
    "branding:delete",
    "categories:read",
    "roles:read",
    "staff:read",
    "audit:read",
  ],
  finance_admin: [
    "dashboard:read",
    "analytics:read",
    "orders:read",
    "audit:read",
    "users:read",
    "vendors:read",
    "products:read",
    "categories:read",
    "roles:read",
    "staff:read",
    "payments:read",
    "payments:refund",
    "payouts:read",
    "payouts:process",
    "settlements:read",
    "settings:read",
    "branding:view",
  ],
};

function normalizeRole(role) {
  return String(role || "").trim().toLowerCase();
}

function hasPermission(role, permission) {
  const normalized = String(permission || "").replace(/\./g, ":");
  return (ROLE_PERMISSIONS[normalizeRole(role)] || []).includes(normalized);
}

module.exports = {
  ADMIN_ROLES,
  ROLE_PERMISSIONS,
  hasPermission,
  normalizeRole,
};
