const CORE_CONTAINER_TYPES = [
  "CAROUSEL",
  "GRID",
  "FEATURED_PRODUCTS",
  "BANNER",
  "SLIDER",
  "FLASH_SALE",
  "DEALS_STRIP",
  "MASONRY",
  "CATEGORY_SHOWCASE",
  "BRAND_SHOWCASE",
  "RECENTLY_VIEWED",
  "RECOMMENDED",
  "TRENDING",
  "NEW_ARRIVALS",
  "TOP_RATED",
  "VENDOR_SPOTLIGHT",
  "COMBO_DEALS",
  "VIDEO_PRODUCTS",
];

const PRODUCT_SELECTION_MODES = ["AUTO", "MANUAL"];
const STOREFRONT_SELECTION_MODES = ["AUTO", "MANUAL"];
const VENDOR_STOREFRONT_TYPES = [
  "VENDOR_STOREFRONT_GRID",
  "VENDOR_STOREFRONT_CAROUSEL",
  "VENDOR_FEATURED_STORES",
  "VENDOR_TRENDING_STORES",
  "VENDOR_VERIFIED_STORES",
  "VENDOR_NEW_STORES",
  "VENDOR_RECOMMENDED_STORES",
];
const INFLUENCER_STOREFRONT_TYPES = [
  "INFLUENCER_STOREFRONT_GRID",
  "INFLUENCER_STOREFRONT_CAROUSEL",
  "INFLUENCER_FEATURED_CREATORS",
  "INFLUENCER_TRENDING_CREATORS",
  "INFLUENCER_VERIFIED_CREATORS",
  "INFLUENCER_NEW_CREATORS",
  "INFLUENCER_RECOMMENDED_CREATORS",
];
const STOREFRONT_CONTAINER_TYPES = [...VENDOR_STOREFRONT_TYPES, ...INFLUENCER_STOREFRONT_TYPES];
const CONTAINER_TYPES = [...CORE_CONTAINER_TYPES, ...STOREFRONT_CONTAINER_TYPES];
const CONTAINER_STATUS = ["DRAFT", "ACTIVE", "DISABLED"];
const SORT_OPTIONS = [
  "BEST_SELLING",
  "HIGHEST_DISCOUNT",
  "NEWEST",
  "TRENDING",
  "PRICE_LOW_TO_HIGH",
  "PRICE_HIGH_TO_LOW",
  "MOST_VIEWED",
  "TOP_RATED",
  "RANDOM",
  "OLDEST",
  "MOST_POPULAR",
  "CUSTOM_ORDER",
];

const PRODUCT_FIELD = {
  type: "async-multiselect",
  source: "products",
  searchable: true,
};

const FIELD_LIBRARY = {
  autoSlide: { type: "boolean", defaultValue: true },
  slideSpeed: { type: "number", min: 1000, max: 20000, defaultValue: 3500 },
  showArrows: { type: "boolean", defaultValue: true },
  showDots: { type: "boolean", defaultValue: true },
  infiniteLoop: { type: "boolean", defaultValue: true },
  productsPerView: { type: "number", min: 1, max: 8, defaultValue: 5 },
  swipeEnabled: { type: "boolean", defaultValue: true },
  showCtaOnHover: { type: "boolean", defaultValue: false },
  desktopColumns: { type: "number", min: 1, max: 8, defaultValue: 4 },
  tabletColumns: { type: "number", min: 1, max: 6, defaultValue: 2 },
  mobileColumns: { type: "number", min: 1, max: 3, defaultValue: 1 },
  gapSize: { type: "number", min: 0, max: 48, defaultValue: 16 },
  cardStyle: {
    type: "select",
    options: ["DEFAULT", "ELEVATED", "MINIMAL", "EDITORIAL"],
    defaultValue: "ELEVATED",
  },
  heroProduct: { ...PRODUCT_FIELD, maxItems: 1 },
  secondaryProducts: { ...PRODUCT_FIELD, maxItems: 6 },
  heroBanner: { type: "text", defaultValue: "" },
  layoutStyle: {
    type: "select",
    options: ["LEFT_HERO", "RIGHT_HERO", "STACKED"],
    defaultValue: "LEFT_HERO",
  },
  featuredHeading: { type: "text", defaultValue: "" },
  featuredSubHeading: { type: "text", defaultValue: "" },
  featuredDescription: { type: "textarea", defaultValue: "" },
  badgeText: { type: "text", defaultValue: "" },
  ctaButtonText: { type: "text", defaultValue: "View all" },
  ctaTarget: { type: "select", options: ["SELF", "BLANK"], defaultValue: "SELF" },
  buttonStyle: { type: "select", options: ["PRIMARY", "SECONDARY", "OUTLINE", "GHOST"], defaultValue: "PRIMARY" },
  featuredLayoutStyle: {
    type: "select",
    options: [
      "LEFT_HERO",
      "RIGHT_HERO",
      "TOP_HERO",
      "BOTTOM_HERO",
      "HERO_PLUS_GRID",
      "HERO_PLUS_CAROUSEL",
      "MAGAZINE_LAYOUT",
      "AMAZON_SHOWCASE",
      "FLIPKART_SHOWCASE",
      "MYNTRA_SHOWCASE",
      "MARKETPLACE_SHOWCASE",
      "CUSTOM_GRID",
    ],
    defaultValue: "LEFT_HERO",
  },
  productSourceMode: {
    type: "select",
    options: ["MANUAL", "CATEGORY_BASED", "BRAND_BASED", "VENDOR_BASED", "BEST_SELLERS", "TRENDING_PRODUCTS", "NEWEST_PRODUCTS", "HIGHEST_RATED_PRODUCTS"],
    defaultValue: "MANUAL",
  },
  productsPerRowDesktop: { type: "select", options: ["2", "3", "4", "5", "6"], defaultValue: "4" },
  productsPerRowTablet: { type: "select", options: ["1", "2", "3", "4"], defaultValue: "2" },
  productsPerRowMobile: { type: "select", options: ["1", "2"], defaultValue: "1" },
  showProductImage: { type: "boolean", defaultValue: true },
  showProductName: { type: "boolean", defaultValue: true },
  showBrand: { type: "boolean", defaultValue: true },
  showPrice: { type: "boolean", defaultValue: true },
  showSalePrice: { type: "boolean", defaultValue: true },
  showRating: { type: "boolean", defaultValue: true },
  showReviewCount: { type: "boolean", defaultValue: true },
  showStockStatus: { type: "boolean", defaultValue: true },
  showWishlist: { type: "boolean", defaultValue: true },
  showQuickView: { type: "boolean", defaultValue: false },
  showCompare: { type: "boolean", defaultValue: false },
  showAddToCart: { type: "boolean", defaultValue: true },
  showDiscountBadge: { type: "boolean", defaultValue: true },
  showBestSellerBadge: { type: "boolean", defaultValue: false },
  showNewArrivalBadge: { type: "boolean", defaultValue: false },
  showLimitedStockBadge: { type: "boolean", defaultValue: true },
  showDeliveryBadge: { type: "boolean", defaultValue: false },
  featuredBackgroundColor: { type: "text", defaultValue: "#ffffff" },
  featuredBackgroundImage: { type: "text", defaultValue: "" },
  borderRadius: { type: "number", min: 0, max: 48, defaultValue: 24 },
  containerPadding: { type: "number", min: 0, max: 120, defaultValue: 32 },
  containerMargin: { type: "number", min: 0, max: 120, defaultValue: 0 },
  gridGap: { type: "number", min: 0, max: 64, defaultValue: 20 },
  cardRadius: { type: "number", min: 0, max: 40, defaultValue: 18 },
  cardShadow: { type: "boolean", defaultValue: true },
  cardBorder: { type: "boolean", defaultValue: true },
  cardHoverEffect: { type: "select", options: ["NONE", "LIFT", "ZOOM", "GLOW"], defaultValue: "LIFT" },
  buttonColor: { type: "text", defaultValue: "#0f172a" },
  buttonTextColor: { type: "text", defaultValue: "#ffffff" },
  headingTextColor: { type: "text", defaultValue: "#0f172a" },
  bodyTextColor: { type: "text", defaultValue: "#475569" },
  overlayColor: { type: "text", defaultValue: "#0f172a" },
  overlayOpacityFeatured: { type: "number", min: 0, max: 1, step: 0.05, defaultValue: 0.08 },
  responsiveDesktopColumns: { type: "number", min: 1, max: 6, defaultValue: 4 },
  responsiveTabletColumns: { type: "number", min: 1, max: 4, defaultValue: 2 },
  responsiveMobileColumns: { type: "number", min: 1, max: 2, defaultValue: 1 },
  minProducts: { type: "number", min: 0, max: 50, defaultValue: 1 },
  productsPerPage: { type: "number", min: 1, max: 50, defaultValue: 12 },
  carouselLimit: { type: "number", min: 1, max: 50, defaultValue: 12 },
  gridLimit: { type: "number", min: 1, max: 50, defaultValue: 12 },
  enableCarousel: { type: "boolean", defaultValue: false },
  autoplaySpeed: { type: "number", min: 1000, max: 20000, defaultValue: 3500 },
  dragSupport: { type: "boolean", defaultValue: true },
  metaTitle: { type: "text", defaultValue: "" },
  metaDescription: { type: "textarea", defaultValue: "" },
  canonicalUrl: { type: "text", defaultValue: "" },
  schemaMarkup: { type: "textarea", defaultValue: "" },
  openGraphTags: { type: "textarea", defaultValue: "" },
  twitterCard: { type: "select", options: ["summary", "summary_large_image"], defaultValue: "summary_large_image" },
  bannerImage: { type: "text", defaultValue: "" },
  bannerVideo: { type: "text", defaultValue: "" },
  bannerMedia: { type: "array", defaultValue: [] },
  heading: { type: "text", defaultValue: "" },
  subheading: { type: "textarea", defaultValue: "" },
  ctaButton: { type: "text", defaultValue: "" },
  ctaUrl: { type: "text", defaultValue: "" },
  overlayOpacity: { type: "number", min: 0, max: 1, step: 0.05, defaultValue: 0.35 },
  textPosition: {
    type: "select",
    options: ["LEFT", "CENTER", "RIGHT"],
    defaultValue: "LEFT",
  },
  slides: { type: "array", defaultValue: [] },
  autoplay: { type: "boolean", defaultValue: true },
  transitionEffect: {
    type: "select",
    options: ["SLIDE", "FADE", "SCALE"],
    defaultValue: "SLIDE",
  },
  indicators: { type: "boolean", defaultValue: true },
  startTime: { type: "datetime", defaultValue: "" },
  endTime: { type: "datetime", defaultValue: "" },
  countdownStyle: {
    type: "select",
    options: ["BLOCKS", "INLINE", "MINIMAL"],
    defaultValue: "BLOCKS",
  },
  flashBanner: { type: "text", defaultValue: "" },
  compactCards: { type: "boolean", defaultValue: true },
  miniLayout: { type: "boolean", defaultValue: true },
  scrollingDeals: { type: "boolean", defaultValue: true },
  dealPrimaryHeading: { type: "text", defaultValue: "" },
  dealSecondaryHeading: { type: "text", defaultValue: "" },
  dealDescription: { type: "textarea", defaultValue: "" },
  offerText: { type: "text", defaultValue: "" },
  dealBadgeText: { type: "text", defaultValue: "" },
  couponCode: { type: "text", defaultValue: "" },
  dealCtaText: { type: "text", defaultValue: "Shop now" },
  dealCtaUrl: { type: "text", defaultValue: "" },
  dealCtaTarget: { type: "select", options: ["SELF", "BLANK"], defaultValue: "SELF" },
  termsAndConditions: { type: "textarea", defaultValue: "" },
  disclaimer: { type: "textarea", defaultValue: "" },
  offerEndDate: { type: "datetime", defaultValue: "" },
  campaignName: { type: "text", defaultValue: "" },
  campaignTag: { type: "text", defaultValue: "" },
  promotionType: {
    type: "select",
    options: ["FLASH_SALE", "COUPON", "BANK_OFFER", "FREE_SHIPPING", "CASHBACK", "LIMITED_TIME", "FESTIVAL_SALE", "SEASONAL_SALE", "NEW_USER_OFFER", "MARKETPLACE_ANNOUNCEMENT", "CUSTOM_PROMOTION"],
    defaultValue: "FLASH_SALE",
  },
  dealLayoutVariant: {
    type: "select",
    options: ["CENTER_BANNER", "LEFT_CONTENT_RIGHT_BUTTON", "COUPON_BANNER", "THREE_COLUMN_STRIP", "SCROLLING_MARQUEE", "COUNTDOWN_BANNER", "MARKETPLACE_PROMO_STRIP"],
    defaultValue: "LEFT_CONTENT_RIGHT_BUTTON",
  },
  dealBackgroundType: { type: "select", options: ["SOLID", "GRADIENT", "IMAGE", "VIDEO"], defaultValue: "GRADIENT" },
  dealBackgroundColor: { type: "text", defaultValue: "#0f172a" },
  dealGradientColor1: { type: "text", defaultValue: "#e11d48" },
  dealGradientColor2: { type: "text", defaultValue: "#f97316" },
  dealBackgroundImage: { type: "image", defaultValue: "" },
  dealBackgroundVideo: { type: "video", defaultValue: "" },
  dealOverlayColor: { type: "text", defaultValue: "#0f172a" },
  dealOverlayOpacity: { type: "number", min: 0, max: 1, step: 0.05, defaultValue: 0.25 },
  dealTextColor: { type: "text", defaultValue: "#ffffff" },
  dealHeadingColor: { type: "text", defaultValue: "#ffffff" },
  dealButtonColor: { type: "text", defaultValue: "#ffffff" },
  dealButtonTextColor: { type: "text", defaultValue: "#0f172a" },
  dealButtonHoverColor: { type: "text", defaultValue: "#f8fafc" },
  dealBorderColor: { type: "text", defaultValue: "rgba(255,255,255,0.22)" },
  dealShadow: { type: "boolean", defaultValue: true },
  dealBorderRadius: { type: "number", min: 0, max: 64, defaultValue: 28 },
  dealPadding: { type: "number", min: 0, max: 120, defaultValue: 28 },
  dealMargin: { type: "number", min: 0, max: 120, defaultValue: 0 },
  dealHeight: { type: "number", min: 0, max: 700, defaultValue: 0 },
  dealWidth: { type: "select", options: ["FULL", "BOXED", "NARROW"], defaultValue: "FULL" },
  dealAlignment: { type: "select", options: ["LEFT", "CENTER", "RIGHT"], defaultValue: "LEFT" },
  dealIcon: { type: "select", options: ["FLASH", "GIFT", "DISCOUNT", "COUPON", "TRUCK", "WALLET", "BANK", "CREDIT_CARD", "CASHBACK", "FESTIVAL", "FIRE", "LIGHTNING", "ANNOUNCEMENT", "CUSTOM"], defaultValue: "FLASH" },
  dealCustomIconImage: { type: "image", defaultValue: "" },
  enableCountdown: { type: "boolean", defaultValue: false },
  countdownStartDate: { type: "datetime", defaultValue: "" },
  countdownEndDate: { type: "datetime", defaultValue: "" },
  countdownTimezone: { type: "text", defaultValue: "Asia/Calcutta" },
  countdownAutoExpire: { type: "boolean", defaultValue: false },
  countdownAutoHide: { type: "boolean", defaultValue: false },
  countdownAutoReplace: { type: "boolean", defaultValue: false },
  timerStyle: { type: "select", options: ["DIGITAL", "COMPACT", "MINIMAL"], defaultValue: "DIGITAL" },
  showDealCta: { type: "boolean", defaultValue: true },
  dealButtonStyle: { type: "select", options: ["FILLED", "OUTLINE", "GHOST", "GRADIENT"], defaultValue: "FILLED" },
  dealButtonIconPosition: { type: "select", options: ["LEFT", "RIGHT"], defaultValue: "RIGHT" },
  dealDesktopHeight: { type: "number", min: 0, max: 700, defaultValue: 0 },
  dealTabletHeight: { type: "number", min: 0, max: 700, defaultValue: 0 },
  dealMobileHeight: { type: "number", min: 0, max: 700, defaultValue: 0 },
  dealDesktopPadding: { type: "number", min: 0, max: 120, defaultValue: 32 },
  dealTabletPadding: { type: "number", min: 0, max: 100, defaultValue: 24 },
  dealMobilePadding: { type: "number", min: 0, max: 80, defaultValue: 18 },
  dealDesktopFontSize: { type: "number", min: 12, max: 72, defaultValue: 34 },
  dealTabletFontSize: { type: "number", min: 12, max: 60, defaultValue: 28 },
  dealMobileFontSize: { type: "number", min: 12, max: 42, defaultValue: 22 },
  dealSpacing: { type: "number", min: 0, max: 64, defaultValue: 16 },
  dealAnimation: { type: "select", options: ["FADE", "SLIDE", "ZOOM", "PULSE", "BOUNCE", "MARQUEE", "BLINK", "GLOW", "NONE"], defaultValue: "FADE" },
  showForGuests: { type: "boolean", defaultValue: true },
  showForLoggedUsers: { type: "boolean", defaultValue: true },
  showForVendors: { type: "boolean", defaultValue: true },
  showForCustomers: { type: "boolean", defaultValue: true },
  showForNewUsers: { type: "boolean", defaultValue: true },
  showForReturningUsers: { type: "boolean", defaultValue: true },
  targetRoles: { type: "text", defaultValue: "" },
  targetCountries: { type: "text", defaultValue: "" },
  targetStates: { type: "text", defaultValue: "" },
  targetCities: { type: "text", defaultValue: "" },
  targetCustomerSegments: { type: "text", defaultValue: "" },
  minCartValue: { type: "number", min: 0, max: 10000000, defaultValue: 0 },
  recurringSchedule: { type: "text", defaultValue: "" },
  autoPublish: { type: "boolean", defaultValue: false },
  autoExpire: { type: "boolean", defaultValue: false },
  columnCount: { type: "number", min: 2, max: 6, defaultValue: 4 },
  cardHeights: {
    type: "select",
    options: ["AUTO", "MIXED", "TALL", "WIDE"],
    defaultValue: "MIXED",
  },
  masonryImage: { type: "image", defaultValue: "" },
  masonryImageHeight: { type: "number", min: 120, max: 700, defaultValue: 260 },
  masonryImagePattern: {
    type: "select",
    options: ["MIXED", "BALANCED", "TALL", "WIDE"],
    defaultValue: "MIXED",
  },
  categories: {
    type: "async-multiselect",
    source: "categories",
    searchable: true,
    defaultValue: [],
  },
  categoryBanner: { type: "text", defaultValue: "" },
  categoryLayout: {
    type: "select",
    options: ["CARDS", "STRIP", "EDITORIAL", "COMPACT_GRID"],
    defaultValue: "CARDS",
  },
  categoryColumns: { type: "number", min: 2, max: 6, defaultValue: 4 },
  categoryShowProductCount: { type: "boolean", defaultValue: true },
  categoryShowDescription: { type: "boolean", defaultValue: true },
  categoryCtaText: { type: "text", defaultValue: "Shop now" },
  categoryCards: { type: "category-cards", defaultValue: [] },
  brands: {
    type: "tags",
    defaultValue: [],
  },
  brandLogos: {
    type: "array",
    defaultValue: [],
  },
  brandBanner: { type: "text", defaultValue: "" },
  historyDuration: { type: "number", min: 1, max: 365, defaultValue: 30 },
  recommendationLogic: {
    type: "select",
    options: ["CATEGORY_AFFINITY", "TOP_SELLERS", "MANUAL"],
    defaultValue: "CATEGORY_AFFINITY",
  },
  manualOverride: { type: "boolean", defaultValue: false },
  viewThreshold: { type: "number", min: 1, max: 100000, defaultValue: 100 },
  salesThreshold: { type: "number", min: 1, max: 100000, defaultValue: 10 },
  trendingLogic: {
    type: "select",
    options: ["VIEWS", "SALES", "HYBRID"],
    defaultValue: "HYBRID",
  },
  daysRange: { type: "number", min: 1, max: 365, defaultValue: 30 },
  sortLatestFirst: { type: "boolean", defaultValue: true },
  minimumReviews: { type: "number", min: 0, max: 100000, defaultValue: 10 },
  vendorBanner: { type: "text", defaultValue: "" },
  vendorTheme: {
    type: "select",
    options: ["LIGHT", "DARK", "BRAND"],
    defaultValue: "BRAND",
  },
  storefrontDisplayType: {
    type: "select",
    options: ["GRID", "CAROUSEL", "SLIDER", "MASONRY"],
    defaultValue: "GRID",
  },
  storefrontSelectionMode: {
    type: "select",
    options: STOREFRONT_SELECTION_MODES,
    defaultValue: "AUTO",
  },
  manualVendorIds: {
    type: "async-multiselect",
    source: "vendors",
    searchable: true,
    defaultValue: [],
  },
  manualInfluencerIds: {
    type: "async-multiselect",
    source: "influencers",
    searchable: true,
    defaultValue: [],
  },
  vendorAutoRule: {
    type: "select",
    options: ["MOST_FOLLOWED", "TOP_RATED", "BEST_SELLING", "HIGHEST_REVENUE", "NEWEST", "VERIFIED", "RECENTLY_ACTIVE", "RANDOM"],
    defaultValue: "MOST_FOLLOWED",
  },
  influencerAutoRule: {
    type: "select",
    options: ["MOST_FOLLOWED", "MOST_VIEWED", "MOST_REVENUE_GENERATED", "TOP_CONVERTING", "TRENDING", "VERIFIED", "NEWEST", "RECOMMENDED", "RANDOM"],
    defaultValue: "MOST_FOLLOWED",
  },
  maxStorefrontCards: { type: "number", min: 1, max: 48, defaultValue: 8 },
  desktopCardCount: { type: "number", min: 1, max: 8, defaultValue: 4 },
  tabletCardCount: { type: "number", min: 1, max: 4, defaultValue: 2 },
  mobileCardCount: { type: "number", min: 1, max: 2, defaultValue: 1 },
  storefrontCardStyle: {
    type: "select",
    options: ["CLASSIC", "MODERN", "MINIMAL", "PREMIUM", "CREATOR"],
    defaultValue: "MODERN",
  },
  storefrontCardLayout: {
    type: "select",
    options: ["VERTICAL", "HORIZONTAL", "OVERLAY", "CREATOR", "STORE_SHOWCASE"],
    defaultValue: "VERTICAL",
  },
  storefrontSortOrder: {
    type: "select",
    options: ["AUTO", "MANUAL_ORDER", "NEWEST", "MOST_FOLLOWED", "TOP_RATED", "RANDOM"],
    defaultValue: "AUTO",
  },
  cardCtaText: { type: "text", defaultValue: "View Store" },
  showStoreLogo: { type: "boolean", defaultValue: true },
  showStoreBanner: { type: "boolean", defaultValue: true },
  showStoreName: { type: "boolean", defaultValue: true },
  showStoreDescription: { type: "boolean", defaultValue: true },
  showStoreCategory: { type: "boolean", defaultValue: true },
  showProductsCount: { type: "boolean", defaultValue: true },
  showFollowersCount: { type: "boolean", defaultValue: true },
  showStoreRating: { type: "boolean", defaultValue: true },
  showReviewsCount: { type: "boolean", defaultValue: true },
  showYearsActive: { type: "boolean", defaultValue: false },
  showVerifiedBadge: { type: "boolean", defaultValue: true },
  showFeaturedBadge: { type: "boolean", defaultValue: true },
  showTopCreatorBadge: { type: "boolean", defaultValue: true },
  showStorefrontCta: { type: "boolean", defaultValue: true },
  animatedEntry: { type: "boolean", defaultValue: true },
  hoverEffect: { type: "boolean", defaultValue: true },
  bundleProducts: { ...PRODUCT_FIELD, defaultValue: [] },
  comboDiscount: { type: "number", min: 0, max: 100, defaultValue: 10 },
  comboTitle: { type: "text", defaultValue: "" },
  comboSubtitle: { type: "text", defaultValue: "" },
  comboBadgeText: { type: "text", defaultValue: "Bundle deal" },
  comboCtaText: { type: "text", defaultValue: "View combo" },
  comboCtaUrl: { type: "text", defaultValue: "" },
  comboBanner: { type: "text", defaultValue: "" },
  comboLayout: { type: "select", options: ["HERO_BUNDLE", "PRODUCT_GRID", "COMPACT_STRIP"], defaultValue: "HERO_BUNDLE" },
  comboShowSavings: { type: "boolean", defaultValue: true },
  comboShowProducts: { type: "boolean", defaultValue: true },
  comboMaxProducts: { type: "number", min: 2, max: 8, defaultValue: 4 },
  videoUpload: { type: "text", defaultValue: "" },
  mute: { type: "boolean", defaultValue: true },
  videoPosition: {
    type: "select",
    options: ["TOP", "LEFT", "RIGHT", "BACKGROUND"],
    defaultValue: "TOP",
  },
};

function field(name, overrides = {}) {
  return {
    name,
    label: name
      .replace(/([A-Z])/g, " $1")
      .replace(/^./, (char) => char.toUpperCase()),
    ...FIELD_LIBRARY[name],
    ...overrides,
  };
}

const PRODUCT_TYPE_DEFAULTS = {
  supportsProducts: true,
  supportsManualSelection: true,
  supportsProductFilters: true,
  defaultSortBy: "TRENDING",
};

function labelFromContainerType(type, prefix) {
  return String(type || "")
    .replace(new RegExp(`^${prefix}_`), `${prefix[0]}${prefix.slice(1).toLowerCase()} `)
    .replace(/_/g, " ")
    .replace(/\b\w/g, (char) => char.toUpperCase());
}

function storefrontFields({
  entity,
  manualField,
  autoRuleField,
  ctaText,
  cardStyleOptions,
  cardLayoutOptions,
  displayNameLabel,
  logoLabel,
  bannerLabel,
  descriptionLabel,
  ratingLabel,
  extraBadgeField,
  extraBadgeLabel,
} = {}) {
  return (type) => [
    field("storefrontDisplayType", { label: "Display Type", defaultValue: type.includes("CAROUSEL") ? "CAROUSEL" : "GRID" }),
    field("storefrontSelectionMode", { label: "Selection Mode" }),
    field(manualField, { label: `Manual ${entity}s` }),
    field(autoRuleField, { label: `Automatic ${entity} Rule` }),
    field("maxStorefrontCards", { label: "Maximum Cards" }),
    field("desktopCardCount", { label: "Desktop Count" }),
    field("tabletCardCount", { label: "Tablet Count" }),
    field("mobileCardCount", { label: "Mobile Count" }),
    field("storefrontCardStyle", { label: "Card Style", options: cardStyleOptions }),
    field("storefrontCardLayout", { label: "Card Layout", options: cardLayoutOptions }),
    field("storefrontSortOrder", { label: "Sort Order" }),
    field("cardCtaText", { label: "Button Text", defaultValue: ctaText }),
    field("showStoreLogo", { label: logoLabel }),
    field("showStoreBanner", { label: bannerLabel }),
    field("showStoreName", { label: displayNameLabel }),
    field("showStoreDescription", { label: descriptionLabel }),
    field("showStoreCategory", { label: "Store Category" }),
    field("showProductsCount", { label: "Products Count" }),
    field("showFollowersCount", { label: "Followers Count" }),
    field("showStoreRating", { label: ratingLabel }),
    field("showReviewsCount", { label: "Reviews Count" }),
    field("showYearsActive", { label: "Years Active" }),
    field("showVerifiedBadge", { label: "Verified Badge" }),
    field(extraBadgeField, { label: extraBadgeLabel }),
    field("showStorefrontCta", { label: "CTA Button" }),
    field("hoverEffect", { label: "Hover Effects" }),
    field("animatedEntry", { label: "Animated Entry" }),
  ];
}

function storefrontRegistryEntries(types, options) {
  const buildFields = storefrontFields(options);
  return Object.fromEntries(
    types.map((type) => [
      type,
      {
        label: labelFromContainerType(type, options.prefix),
        supportsProducts: false,
        supportsManualSelection: true,
        supportsProductFilters: false,
        fields: buildFields(type),
      },
    ])
  );
}

const REGISTRY = {
  CAROUSEL: {
    ...PRODUCT_TYPE_DEFAULTS,
    label: "Carousel",
    fields: [field("autoSlide"), field("slideSpeed"), field("showArrows"), field("showDots"), field("infiniteLoop"), field("productsPerView"), field("swipeEnabled")],
  },
  GRID: {
    ...PRODUCT_TYPE_DEFAULTS,
    label: "Grid",
    fields: [field("desktopColumns"), field("tabletColumns"), field("mobileColumns"), field("gapSize"), field("cardStyle")],
  },
  FEATURED_PRODUCTS: {
    ...PRODUCT_TYPE_DEFAULTS,
    label: "Featured Products",
    defaultSortBy: "TRENDING",
    fields: [
      field("featuredHeading", { label: "Heading" }),
      field("featuredSubHeading", { label: "Sub Heading" }),
      field("featuredDescription", { label: "Description" }),
      field("badgeText"),
      field("ctaButtonText", { label: "CTA Button Text" }),
      field("ctaUrl", { label: "CTA URL" }),
      field("ctaTarget", { label: "CTA Target" }),
      field("buttonStyle"),
      field("productSourceMode"),
      field("heroProduct", { label: "Hero Product", maxItems: 1 }),
      field("secondaryProducts", { label: "Secondary Products", maxItems: 50 }),
      field("productsPerRowDesktop"),
      field("productsPerRowTablet"),
      field("productsPerRowMobile"),
      field("featuredLayoutStyle", { label: "Layout Style" }),
      field("showProductImage"),
      field("showProductName"),
      field("showBrand"),
      field("showPrice"),
      field("showSalePrice"),
      field("showRating"),
      field("showReviewCount"),
      field("showStockStatus"),
      field("showWishlist"),
      field("showQuickView"),
      field("showCompare"),
      field("showAddToCart"),
      field("showDiscountBadge"),
      field("showBestSellerBadge"),
      field("showNewArrivalBadge"),
      field("showLimitedStockBadge"),
      field("showDeliveryBadge"),
      field("featuredBackgroundColor", { label: "Background Color" }),
      field("featuredBackgroundImage", { label: "Background Image" }),
      field("borderRadius"),
      field("containerPadding"),
      field("containerMargin"),
      field("gridGap"),
      field("cardRadius"),
      field("cardShadow"),
      field("cardBorder"),
      field("cardHoverEffect"),
      field("buttonColor", { label: "Button Color" }),
      field("buttonTextColor", { label: "Button Text Color" }),
      field("headingTextColor", { label: "Heading Text Color" }),
      field("bodyTextColor", { label: "Body Text Color" }),
      field("overlayColor"),
      field("overlayOpacityFeatured", { label: "Overlay Opacity" }),
      field("responsiveDesktopColumns", { label: "Desktop Grid Columns" }),
      field("responsiveTabletColumns", { label: "Tablet Grid Columns" }),
      field("responsiveMobileColumns", { label: "Mobile Grid Columns" }),
      field("minProducts"),
      field("productsPerPage"),
      field("carouselLimit"),
      field("gridLimit"),
      field("enableCarousel"),
      field("autoplay"),
      field("autoplaySpeed"),
      field("infiniteLoop"),
      field("showArrows"),
      field("showDots"),
      field("swipeEnabled"),
      field("dragSupport"),
      field("metaTitle"),
      field("metaDescription"),
      field("canonicalUrl"),
      field("schemaMarkup"),
      field("openGraphTags"),
      field("twitterCard"),
    ],
  },
  BANNER: {
    label: "Banner",
    supportsProducts: false,
    supportsManualSelection: false,
    supportsProductFilters: false,
    fields: [
      field("bannerMedia", { label: "Banner Media" }),
      field("overlayOpacity"),
      field("textPosition"),
      field("autoSlide"),
      field("slideSpeed"),
      field("showArrows"),
      field("showDots"),
      field("infiniteLoop"),
      field("swipeEnabled"),
      field("showCtaOnHover", { label: "Show Shop Now On Hover" }),
    ],
  },
  SLIDER: {
    label: "Slider",
    supportsProducts: false,
    supportsManualSelection: false,
    supportsProductFilters: false,
    fields: [field("slides"), field("autoplay"), field("transitionEffect"), field("indicators")],
  },
  FLASH_SALE: {
    ...PRODUCT_TYPE_DEFAULTS,
    label: "Flash Sale",
    defaultSortBy: "HIGHEST_DISCOUNT",
    fields: [field("startTime"), field("endTime"), field("countdownStyle"), field("flashBanner")],
  },
  DEALS_STRIP: {
    ...PRODUCT_TYPE_DEFAULTS,
    label: "Deals Strip",
    defaultSortBy: "HIGHEST_DISCOUNT",
    fields: [
      field("dealPrimaryHeading", { label: "Primary Heading" }),
      field("dealSecondaryHeading", { label: "Secondary Heading" }),
      field("dealDescription", { label: "Description" }),
      field("offerText"),
      field("dealBadgeText", { label: "Badge Text" }),
      field("couponCode"),
      field("dealCtaText", { label: "CTA Text" }),
      field("dealCtaUrl", { label: "CTA URL" }),
      field("dealCtaTarget", { label: "CTA Target" }),
      field("termsAndConditions", { label: "Terms & Conditions" }),
      field("disclaimer"),
      field("offerEndDate"),
      field("campaignName"),
      field("campaignTag"),
      field("promotionType"),
      field("dealLayoutVariant", { label: "Layout Variant" }),
      field("dealIcon", { label: "Icon" }),
      field("dealCustomIconImage", { label: "Custom Icon Image" }),
      field("dealBackgroundType", { label: "Background Type" }),
      field("dealBackgroundColor", { label: "Background Color" }),
      field("dealGradientColor1", { label: "Gradient Color 1" }),
      field("dealGradientColor2", { label: "Gradient Color 2" }),
      field("dealBackgroundImage", { label: "Background Image" }),
      field("dealBackgroundVideo", { label: "Background Video" }),
      field("dealOverlayColor", { label: "Overlay Color" }),
      field("dealOverlayOpacity", { label: "Overlay Opacity" }),
      field("dealTextColor", { label: "Text Color" }),
      field("dealHeadingColor", { label: "Heading Color" }),
      field("dealButtonColor", { label: "Button Color" }),
      field("dealButtonTextColor", { label: "Button Text Color" }),
      field("dealButtonHoverColor", { label: "Button Hover Color" }),
      field("dealBorderColor", { label: "Border Color" }),
      field("dealShadow", { label: "Shadow" }),
      field("dealBorderRadius", { label: "Border Radius" }),
      field("dealPadding", { label: "Padding" }),
      field("dealMargin", { label: "Margin" }),
      field("dealHeight", { label: "Height" }),
      field("dealWidth", { label: "Width" }),
      field("dealAlignment", { label: "Alignment" }),
      field("enableCountdown"),
      field("countdownStartDate", { label: "Countdown Start Date" }),
      field("countdownEndDate", { label: "Countdown End Date" }),
      field("countdownTimezone", { label: "Timezone" }),
      field("countdownAutoExpire", { label: "Auto Expire" }),
      field("countdownAutoHide", { label: "Auto Hide" }),
      field("countdownAutoReplace", { label: "Auto Replace" }),
      field("timerStyle"),
      field("showDealCta", { label: "Show CTA" }),
      field("dealButtonStyle", { label: "Button Style" }),
      field("dealButtonIconPosition", { label: "Icon Position" }),
      field("dealDesktopHeight", { label: "Desktop Height" }),
      field("dealTabletHeight", { label: "Tablet Height" }),
      field("dealMobileHeight", { label: "Mobile Height" }),
      field("dealDesktopPadding", { label: "Desktop Padding" }),
      field("dealTabletPadding", { label: "Tablet Padding" }),
      field("dealMobilePadding", { label: "Mobile Padding" }),
      field("dealDesktopFontSize", { label: "Desktop Font Size" }),
      field("dealTabletFontSize", { label: "Tablet Font Size" }),
      field("dealMobileFontSize", { label: "Mobile Font Size" }),
      field("dealSpacing", { label: "Spacing" }),
      field("dealAnimation", { label: "Animation" }),
      field("showForGuests"),
      field("showForLoggedUsers"),
      field("showForVendors"),
      field("showForCustomers"),
      field("showForNewUsers"),
      field("showForReturningUsers"),
      field("targetRoles", { label: "Specific Roles" }),
      field("targetCountries", { label: "Target Countries" }),
      field("targetStates", { label: "Target States" }),
      field("targetCities", { label: "Target Cities" }),
      field("targetCustomerSegments", { label: "Customer Segments" }),
      field("minCartValue", { label: "Minimum Cart Value" }),
      field("recurringSchedule"),
      field("autoPublish"),
      field("autoExpire"),
      field("metaTitle"),
      field("metaDescription"),
      field("canonicalUrl"),
      field("schemaMarkup"),
      field("openGraphTags"),
      field("twitterCard"),
      field("compactCards"),
      field("miniLayout"),
      field("scrollingDeals"),
    ],
  },
  MASONRY: {
    ...PRODUCT_TYPE_DEFAULTS,
    label: "Masonry",
    fields: [
      field("columnCount", { label: "Desktop Columns" }),
      field("tabletColumns", { label: "Tablet Columns" }),
      field("mobileColumns", { label: "Mobile Columns", max: 2 }),
      field("masonryImage", { label: "Masonry Image" }),
      field("masonryImageHeight", { label: "Masonry Image Height" }),
      field("cardHeights", { label: "Card Height Mix" }),
      field("masonryImagePattern", { label: "Image Pattern" }),
      field("gapSize"),
      field("cardStyle"),
      field("maxProducts", { type: "number", min: 1, max: 50, defaultValue: 24 }),
    ],
  },
  CATEGORY_SHOWCASE: {
    ...PRODUCT_TYPE_DEFAULTS,
    label: "Category Showcase",
    fields: [
      field("categories"),
      field("categoryCards", { label: "Category Cards" }),
      field("categoryBanner", { type: "image", label: "Category Banner" }),
      field("categoryLayout"),
      field("categoryColumns", { label: "Desktop Columns" }),
      field("categoryShowProductCount", { label: "Show Product Count" }),
      field("categoryShowDescription", { label: "Show Description" }),
      field("categoryCtaText", { label: "CTA Text" }),
      field("gapSize"),
    ],
  },
  BRAND_SHOWCASE: {
    ...PRODUCT_TYPE_DEFAULTS,
    label: "Brand Showcase",
    fields: [field("brands"), field("brandLogos"), field("brandBanner")],
  },
  RECENTLY_VIEWED: {
    ...PRODUCT_TYPE_DEFAULTS,
    label: "Recently Viewed",
    fields: [field("historyDuration"), field("maxProducts", { type: "number", min: 1, max: 50, defaultValue: 12 })],
  },
  RECOMMENDED: {
    ...PRODUCT_TYPE_DEFAULTS,
    label: "Recommended",
    fields: [field("recommendationLogic"), field("manualOverride")],
  },
  TRENDING: {
    ...PRODUCT_TYPE_DEFAULTS,
    label: "Trending",
    defaultSortBy: "TRENDING",
    fields: [field("viewThreshold"), field("salesThreshold"), field("trendingLogic")],
  },
  NEW_ARRIVALS: {
    ...PRODUCT_TYPE_DEFAULTS,
    label: "New Arrivals",
    defaultSortBy: "NEWEST",
    fields: [field("daysRange"), field("sortLatestFirst")],
  },
  TOP_RATED: {
    ...PRODUCT_TYPE_DEFAULTS,
    label: "Top Rated",
    defaultSortBy: "TOP_RATED",
    fields: [field("minimumRating", { type: "number", min: 0, max: 5, step: 0.1, defaultValue: 4 }), field("minimumReviews")],
  },
  VENDOR_SPOTLIGHT: {
    ...PRODUCT_TYPE_DEFAULTS,
    label: "Vendor Spotlight",
    fields: [field("vendorBanner"), field("vendorTheme")],
  },
  ...storefrontRegistryEntries(VENDOR_STOREFRONT_TYPES, {
    prefix: "VENDOR",
    entity: "Vendor",
    manualField: "manualVendorIds",
    autoRuleField: "vendorAutoRule",
    ctaText: "View Store",
    cardStyleOptions: ["CLASSIC", "MODERN", "MINIMAL", "PREMIUM"],
    cardLayoutOptions: ["VERTICAL", "HORIZONTAL", "OVERLAY", "STORE_SHOWCASE"],
    displayNameLabel: "Store Name",
    logoLabel: "Store Logo",
    bannerLabel: "Store Banner",
    descriptionLabel: "Store Description",
    ratingLabel: "Rating",
    extraBadgeField: "showFeaturedBadge",
    extraBadgeLabel: "Featured Badge",
  }),
  ...storefrontRegistryEntries(INFLUENCER_STOREFRONT_TYPES, {
    prefix: "INFLUENCER",
    entity: "Influencer",
    manualField: "manualInfluencerIds",
    autoRuleField: "influencerAutoRule",
    ctaText: "View Storefront",
    cardStyleOptions: ["CLASSIC", "MODERN", "CREATOR", "PREMIUM"],
    cardLayoutOptions: ["VERTICAL", "HORIZONTAL", "OVERLAY", "CREATOR"],
    displayNameLabel: "Display Name",
    logoLabel: "Profile Photo",
    bannerLabel: "Cover Banner",
    descriptionLabel: "Bio",
    ratingLabel: "Engagement Score",
    extraBadgeField: "showTopCreatorBadge",
    extraBadgeLabel: "Top Creator Badge",
  }),
  COMBO_DEALS: {
    ...PRODUCT_TYPE_DEFAULTS,
    label: "Combo Deals",
    fields: [
      field("comboTitle", { label: "Combo Title" }),
      field("comboSubtitle", { label: "Combo Subtitle" }),
      field("comboBadgeText", { label: "Badge Text" }),
      field("bundleProducts"),
      field("comboDiscount"),
      field("comboBanner", { type: "image", label: "Combo Banner" }),
      field("comboLayout"),
      field("comboShowSavings", { label: "Show Savings" }),
      field("comboShowProducts", { label: "Show Products" }),
      field("comboMaxProducts", { label: "Maximum Bundle Products" }),
      field("comboCtaText", { label: "CTA Text" }),
      field("comboCtaUrl", { label: "CTA URL" }),
    ],
  },
  VIDEO_PRODUCTS: {
    ...PRODUCT_TYPE_DEFAULTS,
    label: "Video Products",
    fields: [field("videoUpload"), field("autoplay"), field("mute"), field("videoPosition")],
  },
};

const TYPE_ALIASES = {
  PRODUCT_CAROUSEL: "CAROUSEL",
};

function normalizeContainerType(type) {
  const normalized = String(type || "CAROUSEL").trim().toUpperCase();
  return TYPE_ALIASES[normalized] || normalized;
}

const COMMON_FIELDS = [
  { name: "title", label: "Container Name", type: "text", required: true },
  { name: "slug", label: "Slug", type: "text", required: true },
  { name: "description", label: "Description", type: "textarea" },
  { name: "containerType", label: "Container Type", type: "select", options: CONTAINER_TYPES, required: true },
  { name: "priority", label: "Priority", type: "number", defaultValue: 0 },
  { name: "status", label: "Status", type: "select", options: CONTAINER_STATUS, defaultValue: "DRAFT" },
  { name: "scheduleStart", label: "Schedule Start", type: "datetime" },
  { name: "scheduleEnd", label: "Schedule End", type: "datetime" },
  { name: "desktopVisible", label: "Desktop Visibility", type: "boolean", defaultValue: true },
  { name: "mobileVisible", label: "Mobile Visibility", type: "boolean", defaultValue: true },
  { name: "backgroundColor", label: "Background Color", type: "text", defaultValue: "" },
  { name: "textColor", label: "Text Color", type: "text", defaultValue: "" },
  { name: "padding", label: "Padding", type: "text", defaultValue: "24px" },
  { name: "margin", label: "Margin", type: "text", defaultValue: "0" },
  { name: "animation", label: "Animation", type: "select", options: ["NONE", "FADE_UP", "FADE_IN", "SLIDE_LEFT", "SLIDE_RIGHT"], defaultValue: "FADE_UP" },
  { name: "customCssClasses", label: "Custom CSS Classes", type: "text", defaultValue: "" },
  { name: "containerWidth", label: "Container Width", type: "text", defaultValue: "full" },
  { name: "containerOffsetX", label: "Offset X", type: "text", defaultValue: "" },
  { name: "containerOffsetY", label: "Offset Y", type: "text", defaultValue: "" },
  { name: "containerHeight", label: "Container Height", type: "text", defaultValue: "auto" },
  { name: "containerTheme", label: "Container Theme", type: "select", options: ["DEFAULT", "LIGHT", "DARK", "BRAND"], defaultValue: "DEFAULT" },
];

const PRODUCT_FILTER_FIELDS = [
  { name: "vendorIds", label: "Vendors", type: "async-multiselect", source: "vendors", searchable: true },
  { name: "categoryIds", label: "Categories", type: "async-multiselect", source: "categories", searchable: true },
  { name: "subCategoryIds", label: "Subcategories", type: "async-multiselect", source: "subcategories", searchable: true },
  { name: "brandIds", label: "Brands", type: "async-multiselect", source: "brands", searchable: true },
  { name: "tags", label: "Tags", type: "async-multiselect", source: "tags", searchable: true },
  { name: "minPrice", label: "Min Price", type: "number", min: 0 },
  { name: "maxPrice", label: "Max Price", type: "number", min: 0 },
  { name: "minDiscountPercentage", label: "Offer Percentage", type: "number", min: 0, max: 100, defaultValue: 0 },
  { name: "minimumRating", label: "Minimum Rating", type: "number", min: 0, max: 5, step: 0.1, defaultValue: 0 },
  { name: "showOnlyInStock", label: "Stock Filter", type: "boolean", defaultValue: true },
  { name: "sortBy", label: "Sort By", type: "select", options: SORT_OPTIONS, defaultValue: "TRENDING" },
  { name: "maxProductsToShow", label: "Maximum Products", type: "number", min: 1, max: 100, defaultValue: 12 },
  { name: "productSelectionMode", label: "Product Selection Mode", type: "select", options: PRODUCT_SELECTION_MODES, defaultValue: "AUTO" },
  { name: "manualProductIds", label: "Manual Products", type: "async-multiselect", source: "products", searchable: true },
];

function getContainerTypeConfig(type) {
  return REGISTRY[normalizeContainerType(type)] || REGISTRY.CAROUSEL;
}

function getContainerTypeSchema(type) {
  const normalizedType = normalizeContainerType(type);
  const typeConfig = getContainerTypeConfig(normalizedType);

  return {
    type: normalizedType,
    label: typeConfig.label,
    supportsProducts: Boolean(typeConfig.supportsProducts),
    supportsManualSelection: Boolean(typeConfig.supportsManualSelection),
    supportsProductFilters: Boolean(typeConfig.supportsProductFilters),
    defaultSortBy: typeConfig.defaultSortBy || "TRENDING",
    commonFields: COMMON_FIELDS,
    productFilterFields: typeConfig.supportsProductFilters ? PRODUCT_FILTER_FIELDS : [],
    typeFields: typeConfig.fields || [],
  };
}

function listContainerTypeSchemas() {
  return CONTAINER_TYPES.map((type) => getContainerTypeSchema(type));
}

module.exports = {
  CONTAINER_TYPES,
  CONTAINER_STATUS,
  PRODUCT_SELECTION_MODES,
  STOREFRONT_SELECTION_MODES,
  VENDOR_STOREFRONT_TYPES,
  INFLUENCER_STOREFRONT_TYPES,
  STOREFRONT_CONTAINER_TYPES,
  SORT_OPTIONS,
  COMMON_FIELDS,
  PRODUCT_FILTER_FIELDS,
  normalizeContainerType,
  getContainerTypeConfig,
  getContainerTypeSchema,
  listContainerTypeSchemas,
};
