import { DEFAULT_GLOBAL_THEME } from "./tokens";

export const CSS_VAR_FALLBACKS = Object.freeze({
  "--color-primary": DEFAULT_GLOBAL_THEME.colors.primary,
  "--color-primary-hover": DEFAULT_GLOBAL_THEME.colors.secondary,
  "--color-secondary": DEFAULT_GLOBAL_THEME.colors.secondary,
  "--color-accent": DEFAULT_GLOBAL_THEME.colors.accent,
  "--color-background": DEFAULT_GLOBAL_THEME.colors.background,
  "--color-surface": DEFAULT_GLOBAL_THEME.colors.surface,
  "--color-surface-secondary": "#f5f5f5",
  "--color-card": DEFAULT_GLOBAL_THEME.colors.card,
  "--color-border": DEFAULT_GLOBAL_THEME.colors.border,
  "--color-text-primary": DEFAULT_GLOBAL_THEME.colors.textPrimary,
  "--color-text-secondary": DEFAULT_GLOBAL_THEME.colors.textSecondary,
  "--color-success": DEFAULT_GLOBAL_THEME.colors.success,
  "--color-warning": DEFAULT_GLOBAL_THEME.colors.warning,
  "--color-danger": DEFAULT_GLOBAL_THEME.colors.danger,
  "--color-info": DEFAULT_GLOBAL_THEME.colors.info,
  "--color-input-text": DEFAULT_GLOBAL_THEME.colors.textPrimary,
  "--color-input-background": "#ffffff",
  "--color-input-placeholder": DEFAULT_GLOBAL_THEME.colors.textSecondary,
  "--font-family": DEFAULT_GLOBAL_THEME.typography.fontFamily,
  "--font-heading": DEFAULT_GLOBAL_THEME.typography.headingFont,
  "--font-body": DEFAULT_GLOBAL_THEME.typography.bodyFont,
  "--font-button": DEFAULT_GLOBAL_THEME.typography.buttonFont,
  "--container-width": DEFAULT_GLOBAL_THEME.spacing.containerWidth,
  "--section-padding": DEFAULT_GLOBAL_THEME.spacing.sectionPadding,
  "--card-padding": DEFAULT_GLOBAL_THEME.spacing.cardPadding,
  "--button-padding": DEFAULT_GLOBAL_THEME.spacing.buttonPadding,
  "--input-padding": DEFAULT_GLOBAL_THEME.spacing.inputPadding,
  "--grid-spacing": DEFAULT_GLOBAL_THEME.spacing.gridSpacing,
  "--radius-card": DEFAULT_GLOBAL_THEME.radius.card,
  "--radius-button": DEFAULT_GLOBAL_THEME.radius.button,
  "--radius-input": DEFAULT_GLOBAL_THEME.radius.input,
  "--radius-modal": DEFAULT_GLOBAL_THEME.radius.modal,
  "--radius-drawer": DEFAULT_GLOBAL_THEME.radius.drawer,
  "--radius-container": DEFAULT_GLOBAL_THEME.radius.container,
  "--radius-small": DEFAULT_GLOBAL_THEME.radius.input,
  "--radius-medium": DEFAULT_GLOBAL_THEME.radius.card,
  "--radius-large": DEFAULT_GLOBAL_THEME.radius.container,
  "--shadow-card": DEFAULT_GLOBAL_THEME.shadows.card,
  "--shadow-hover": DEFAULT_GLOBAL_THEME.shadows.hover,
  "--shadow-modal": DEFAULT_GLOBAL_THEME.shadows.modal,
  "--shadow-button": DEFAULT_GLOBAL_THEME.shadows.button,
  "--shadow-dropdown": DEFAULT_GLOBAL_THEME.shadows.dropdown,
  "--shadow-small": DEFAULT_GLOBAL_THEME.shadows.card,
  "--shadow-medium": DEFAULT_GLOBAL_THEME.shadows.hover,
  "--shadow-large": DEFAULT_GLOBAL_THEME.shadows.modal,
  "--transition-standard": DEFAULT_GLOBAL_THEME.animation.transitionSpeed,
  "--animation-hover": DEFAULT_GLOBAL_THEME.animation.hoverDuration,
  "--animation-page": DEFAULT_GLOBAL_THEME.animation.pageAnimation,
  "--animation-card": DEFAULT_GLOBAL_THEME.animation.cardAnimation,
  "--animation-button": DEFAULT_GLOBAL_THEME.animation.buttonAnimation,
  "--animation-modal": DEFAULT_GLOBAL_THEME.animation.modalAnimation,
  "--animation-reels": DEFAULT_GLOBAL_THEME.animation.reelsAnimation,
  "--commerce-accent": DEFAULT_GLOBAL_THEME.colors.primary,
  "--commerce-accent-soft": "rgba(229, 57, 53, 0.08)",
  "--commerce-accent-warm": DEFAULT_GLOBAL_THEME.colors.accent,
});

export function withCssVarFallbacks(variables = {}) {
  return { ...CSS_VAR_FALLBACKS, ...Object.fromEntries(Object.entries(variables).filter(([, value]) => value != null && value !== "")) };
}
